FROM rocm/pytorch:rocm7.14.1_ubuntu26.04_py3.14_pytorch_release_2.12.0

WORKDIR /app

RUN pip install uv

RUN uv pip install \ 
    transformers \
    evaluate \
    wandb \
    accelerate>=1.1.0 \
    scikit-learn 

CMD ["bash"]