[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "ftt"
version = "1.0.0"
description = "BERT Transformer fine tuning by 640k tweets"
requires-python = ">=3.12"
dependencies = [
    "datasets",
    "dotenv",
    "huggingface-hub",
    "duckdb",
    "lingua-language-detector",
    "scikit-learn",
    "optuna",
    "transformers",
    "evaluate",
    "optimum[onnxruntime]>=1.16.0",
    "sentence-transformers",
    "torch",
    "tqdm",
]

[project.optional-dependencies]
dev = [
    "ipykernel",
]

# uv CPU PyTorch stroage setting
[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cpu" }

[tool.setuptools.packages.find]
where = ["src"]